name: Continuous Integration

on:
    pull_request:
        branches: [main]

jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            # ...
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1

            - run: bun test
